### ISSUE TITLE
Deleted links

### ISSUE THREAD

**Issue by schochastics** [gesiscss/awesome-computational-social-science#20]
- Digital Humanities Lab at UFBA https://www.labhd.ufba.br/ was temporarily removed because it was flagged:
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed` @leofn

**Comment by leofn** [comment]
Sorry, I'm talking with my University...

**Comment by leofn** [comment]
It's okay now: https://www.labhd.ufba.br/
