### ISSUE TITLE
Break "University Course Programs" section into three subsections

### ISSUE THREAD

**Issue by cllei12** [gesiscss/awesome-computational-social-science#59]
Thanks for maintaining such an amazing list!

I wonder if it's possible to break the "University Course Programs" section into three subsections: BS, MS, and PhD? 

PS: I researched PhD programs in computational social science for my application. I'd like to contribute to this section.

**Comment by schochastics** [comment]
Thats a good idea. If you want to give it a try you are more than welcome to do it
