### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by cllei12** [gesiscss/awesome-computational-social-science#65]
URLChecker: 🤔 Uh oh... The following urls did not pass:
❌️ https://web.edu.hku.hk/programme/bsds
❌️ https://github.com/greister/Awesome-Julia

**Comment by schochastics** [comment]
The checker does sometimes bug out. It is unfortunately not very consistent

**Comment by schochastics** [comment]
The checker does sometimes bug out. It is unfortunately not very consistent.

Though these seem indeed broken
